I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/third_day.rpy", line 576, in script
    show bird1 at truecenter_custom
  File "game/scripts/third_day.rpy", line 576, in <module>
    show bird1 at truecenter_custom
NameError: name 'truecenter_custom' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/third_day.rpy", line 576, in script
    show bird1 at truecenter_custom
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 1367, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 1367, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/third_day.rpy", line 576, in <module>
    show bird1 at truecenter_custom
NameError: name 'truecenter_custom' is not defined

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
DGame 1.0
Wed Dec  7 12:32:17 2022
